### ISSUE TITLE
Feature request: Configurable persistent rooms

### ISSUE THREAD

**Issue by urmaul** [philmtd/full-house#270]
I host an instance of full-house to estimate tasks in my team. Creating a new game and spreading a new link every time is a tedious job so I hacked a hardcoded slug that automatically creates a game when opened. This way we can keep a single link in bookmarks and jump directly into the game when opening it.

You can find my hack here: https://github.com/philmtd/full-house/commit/cf8b6e88989d595d2ce22b658c726db8b898dc52

Would be nice to have something like this as a proper feature with ability to define rooms in the config file.

**Comment by philmtd** [comment]
Hi @urmaul, thank you for your idea!

Actually having persistent rooms is a request I also heard a few times from some colleagues at the place I work at.

My wish was to have this feature somehow integrated into the UI and not doing too much via hardcoded configuration. I guess I won't be able to do that soon, though, so maybe I should give a hardcoded configuration a try instead of not implementing it at all.

If I find some spare time in the next few days, I will give it a try.

**Comment by philmtd** [comment]
Hi @urmaul, I created a PR with the feature in #271. Would you mind trying it out briefly and give me short feedback before I create a release? The readme explains how to configure the persistent games. Please let me know if there is anything missing or unclear.

**Comment by urmaul** [comment]
Will do

**Comment by philmtd** [comment]
Thank you for your feedback!

You say:

>  But it doesn't provide a way to overwrite the config file.

Can you elaborate on this? I usually don't run applications with Docker directly but use e.g. Kubernetes. But overriding the configuration file is precisely what I do there (if you care to take a look, it's here in the Helm Chart: https://github.com/philmtd/helm-charts/blob/main/charts/full-house/templates/deployment.yaml#L39).

The same should work when using `docker run -p 8080:8080 -v "my/local/fullhouse.yaml:/app/config/fullhouse.yaml" philmtd/full-house`

**Comment by urmaul** [comment]
For some reason I thought the volume needs to be declared in the Dockerfile if you want to override it later. Probably I'm wrong. It didn't work from the first try and I jumped to conclusions.

**Comment by philmtd** [comment]
Thanks! No, it does not need to be declared. And yes, it's e.g. easy to mess up the paths of the files. Had this half an hour ago and was already about to try to fix a bug that did not exist because I was in the wrong directory in my terminal...

**Comment by philmtd** [comment]
Just released it as version 1.7.0.
